name: Publish Python bindings

on:
  release:
    types: [created]

jobs:

  linux-p39:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.6.0
          manylinux: 2014
          command: publish
          args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.9

  linux-p310:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.6.0
          manylinux: 2014
          command: publish
          args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.10

  linux-p311:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.6.0
          manylinux: 2014
          command: publish
          args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.11

  linux-p312:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - uses: PyO3/maturin-action@v1
        with:
          maturin-version: 1.6.0
          manylinux: 2014
          command: publish
          args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.12

  win-p39:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.9

  win-p310:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.10

  win-p311:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.11        

  win-p312:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.12    

  macos-p39:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist --universal2 -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.9

  macos-p310:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist --universal2 -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.10        

  macos-p311:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist --universal2 -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.11         

  macos-p312:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install aarch64-apple-darwin toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-apple-darwin
    - uses: PyO3/maturin-action@v1
      with:
        maturin-version: 1.6.0
        command: publish
        args: --no-sdist --universal2 -u __token__ -p ${{ secrets.PASSWORD_PYPI }} -i python3.12        